### PR TITLE
Pt translations

### PR DESCRIPTION
**Pull request by hkkobayashi**

### CODE REVIEW

**Comment by timbru** [comment]
Thanks!

**Comment by timbru** [comment]
@hkkobayashi Could you also look at this line? (late addition) 

https://github.com/NLnetLabs/lagosta/blob/master/src/locales/pt.json#L20

How would you say 'edit'? mudar, maybe?

**Comment by hkkobayashi** [comment]
> How would you say 'edit'? mudar, maybe?

You can use "Editar".

**Comment by timbru** [comment]
Ok, I will update master accordingly

**Pull request merged**
