### PR TITLE
Initial pt-br for announcements section

### PR DESCRIPTION
**Pull request by dev-gto**
I have a question regarding roa_seen label.

The original "SEEN" in roa_seen label can be translated to "VISTO", but I'm not sure if it fits in this context. Usually seen is related to some event occurred in the past, but we don't have any date/time event related, such as "latest date/time seen".

Does the label "SEEN" refer to the term "VALID ROAs"?

One missing thing is the label 'Prefix' ('State' is missing too) used in some header tables, and also while adding a ROA.

Thanks & regards,

### CODE REVIEW

**Comment by timbru** [comment]
The label "seen" means that this ROA covers announcements which were seen. As opposed to "stale" if no current announcements are seen.

Both ROAs are valid in the sense of RPKI - but the first is most likely relevant whereas the second is (most likely) not.

In an earlier iteration we differentiated between ROAs which would cause at least one valid announcement and ROAs which cause invalids only. But we decided against this because the first can also cause invalid announcements. Note that in any case the invalid announcements are listed separately as well so you do not have to find them by their causing ROA (they can in fact appear under multiple ROAs).

The labels for the headers are not in the file yet, but if you have alternative terms for them we can make sure to add these as well.

**Comment by dev-gto** [comment]
thanks for this explanation, much appreciated.

Still, I'm not sure about my pt translation, but I can't find a better term for it. Anyway, for the first version, I think we can use it.

For the labels, I would like to suggest en:'prefix' -> pt:'prefixo' and en:'state' -> pt:'estado'

**Comment by timbru** [comment]
Thanks, all merged!

**Comment by timbru** [comment]
We had some more discussion about the label "stale" for ROAs, and in the end re-settled on "unseen" - meaning that there are no announcements seen for this ROA. Should we use something like "NÃO VISTO" instead? Or do you have another suggestion?

**Pull request merged**
