### PR TITLE
Added missing translation

### PR DESCRIPTION
**Pull request by dev-gto**

### CODE REVIEW

**Comment by enricoberti** [comment]
Thanks @dev-gto !

**Comment by timbru** [comment]
Hi @dev-gto 

There were two more strings added since your pull request, could you please have a look at those as well:
https://github.com/NLnetLabs/lagosta/commit/548c9216167c80de9d5b8b39304c962088cf23ba#diff-2225fbeeb5f8293fcd91425cb5799871

    "warning": "Warning",
    "idle": "You have been logged out because of inactivity."

**Comment by dev-gto** [comment]
Sure thing!

**Comment by timbru** [comment]
Thanks, merged it!

**Pull request merged**
